import { db } from './db';
import { generateId, getCurrentTime, getCreditLevel } from './helpers';
import * as bcrypt from 'bcryptjs';

function hashPassword(password: string): string {
  return bcrypt.hashSync(password, 10);
}

const sampleUsers = [
  {
    id: 'user-admin',
    phone: '13800000000',
    email: 'admin@example.com',
    password: hashPassword('admin123'),
    nickname: '管理员',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=admin',
    creditScore: 95,
    creditLevel: 'S',
    timeCoins: 100,
    neighborhood: '阳光花园小区',
    role: 'admin' as const,
    isVerified: true,
    realName: '系统管理员',
    houseNumber: '物业办公室',
    createdAt: getCurrentTime(),
  },
  {
    id: 'user-zhang',
    phone: '13800000001',
    email: 'zhang@example.com',
    password: hashPassword('123456'),
    nickname: '张先生',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=zhang',
    creditScore: 88,
    creditLevel: 'A',
    timeCoins: 25,
    neighborhood: '阳光花园小区',
    role: 'user' as const,
    isVerified: true,
    realName: '张三',
    houseNumber: '3栋2单元502室',
    createdAt: getCurrentTime(),
  },
  {
    id: 'user-li',
    phone: '13800000002',
    email: 'li@example.com',
    password: hashPassword('123456'),
    nickname: '李女士',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=li',
    creditScore: 92,
    creditLevel: 'A',
    timeCoins: 15,
    neighborhood: '阳光花园小区',
    role: 'user' as const,
    isVerified: false,
    createdAt: getCurrentTime(),
  },
  {
    id: 'user-wang',
    phone: '13800000003',
    email: 'wang@example.com',
    password: hashPassword('123456'),
    nickname: '王师傅',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=wang',
    creditScore: 85,
    creditLevel: 'B',
    timeCoins: 30,
    neighborhood: '阳光花园小区',
    role: 'user' as const,
    isVerified: true,
    realName: '王五',
    houseNumber: '1栋1单元301室',
    createdAt: getCurrentTime(),
  },
  {
    id: 'user-chen',
    phone: '13800000004',
    email: 'chen@example.com',
    password: hashPassword('123456'),
    nickname: '陈老师',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=chen',
    creditScore: 90,
    creditLevel: 'A',
    timeCoins: 20,
    neighborhood: '阳光花园小区',
    role: 'user' as const,
    isVerified: false,
    createdAt: getCurrentTime(),
  },
];

const sampleItems = [
  {
    id: 'item-1',
    ownerId: 'user-zhang',
    title: '博世电钻套装',
    description: '专业级电钻套装，含多种钻头，适合家装DIY使用。使用时请注意安全，戴好护目镜。',
    category: '工具',
    images: [] as string[],
    deposit: 200,
    borrowRules: '1. 请轻拿轻放，避免摔碰；2. 使用后请清洁干净；3. 如有损坏照价赔偿。',
    maxBorrowDays: 7,
    minCreditLevel: 'B',
    status: 'available' as const,
    viewCount: 42,
    borrowCount: 8,
    createdAt: getCurrentTime(),
  },
  {
    id: 'item-2',
    ownerId: 'user-li',
    title: '空气炸锅',
    description: '美的空气炸锅，4.5L大容量，可以制作炸鸡、薯条、烤红薯等美食。',
    category: '家电',
    images: [] as string[],
    deposit: 150,
    borrowRules: '1. 使用前请阅读说明书；2. 请保持清洁；3. 请勿空烧。',
    maxBorrowDays: 3,
    minCreditLevel: 'C',
    status: 'available' as const,
    viewCount: 35,
    borrowCount: 12,
    createdAt: getCurrentTime(),
  },
  {
    id: 'item-3',
    ownerId: 'user-wang',
    title: '专业工具箱套装',
    description: '128件综合工具箱，包含螺丝刀、扳手、钳子等各种常用工具。',
    category: '工具',
    images: [] as string[],
    deposit: 300,
    borrowRules: '1. 请按清单核对数量；2. 使用后请归位；3. 如有遗失按价赔偿。',
    maxBorrowDays: 14,
    minCreditLevel: 'A',
    status: 'available' as const,
    viewCount: 56,
    borrowCount: 5,
    createdAt: getCurrentTime(),
  },
  {
    id: 'item-4',
    ownerId: 'user-chen',
    title: '羽毛球拍套装',
    description: '尤尼克斯羽毛球拍两支，附带三个羽毛球和球拍套。',
    category: '运动器材',
    images: [] as string[],
    deposit: 100,
    borrowRules: '1. 请勿用力摔拍；2. 使用后请擦拭干净；3. 羽毛球属消耗品。',
    maxBorrowDays: 5,
    minCreditLevel: 'B',
    status: 'available' as const,
    viewCount: 28,
    borrowCount: 15,
    createdAt: getCurrentTime(),
  },
  {
    id: 'item-5',
    ownerId: 'user-zhang',
    title: '帐篷（4人）',
    description: '牧高笛四人帐篷，防风防雨，适合周末露营使用。',
    category: '运动器材',
    images: [] as string[],
    deposit: 250,
    borrowRules: '1. 请按说明正确搭建；2. 使用后请晾干再收纳；3. 如有破损请告知。',
    maxBorrowDays: 7,
    minCreditLevel: 'B',
    status: 'available' as const,
    viewCount: 45,
    borrowCount: 7,
    createdAt: getCurrentTime(),
  },
  {
    id: 'item-6',
    ownerId: 'user-li',
    title: '编程书籍套装',
    description: 'JavaScript高级程序设计、CSS世界、深入浅出Node.js 共3本',
    category: '图书',
    images: [] as string[],
    deposit: 50,
    borrowRules: '1. 请爱护书籍，不要折页涂画；2. 请按时归还。',
    maxBorrowDays: 30,
    minCreditLevel: 'A',
    status: 'available' as const,
    viewCount: 20,
    borrowCount: 3,
    createdAt: getCurrentTime(),
  },
];

const sampleSkills = [
  {
    id: 'skill-1',
    providerId: 'user-wang',
    title: '水电维修服务',
    description: '专业水电工，可处理水管漏水、电路故障、灯具安装等问题。拥有10年从业经验。',
    category: '维修服务',
    images: [] as string[],
    timeCoinPrice: 5,
    serviceDuration: 60,
    serviceArea: '阳光花园小区及周边1公里',
    status: 'active' as const,
    viewCount: 67,
    createdAt: getCurrentTime(),
  },
  {
    id: 'skill-2',
    providerId: 'user-li',
    title: '宠物代遛',
    description: '爱狗人士，可提供遛狗服务，每天早晚各一次，每次30分钟。',
    category: '家政服务',
    images: [] as string[],
    timeCoinPrice: 3,
    serviceDuration: 30,
    serviceArea: '阳光花园小区',
    status: 'active' as const,
    viewCount: 42,
    createdAt: getCurrentTime(),
  },
  {
    id: 'skill-3',
    providerId: 'user-chen',
    title: '吉他教学',
    description: '音乐专业毕业，有5年教学经验，可提供零基础入门教学。',
    category: '教学辅导',
    images: [] as string[],
    timeCoinPrice: 8,
    serviceDuration: 60,
    serviceArea: '阳光花园小区',
    status: 'active' as const,
    viewCount: 89,
    createdAt: getCurrentTime(),
  },
  {
    id: 'skill-4',
    providerId: 'user-zhang',
    title: '电脑维修',
    description: '可处理电脑系统安装、病毒查杀、硬件升级等问题。',
    category: '维修服务',
    images: [] as string[],
    timeCoinPrice: 4,
    serviceDuration: 60,
    serviceArea: '阳光花园小区',
    status: 'active' as const,
    viewCount: 34,
    createdAt: getCurrentTime(),
  },
  {
    id: 'skill-5',
    providerId: 'user-chen',
    title: '英语辅导',
    description: '英语专业八级，可提供中小学英语辅导、口语练习。',
    category: '教学辅导',
    images: [] as string[],
    timeCoinPrice: 6,
    serviceDuration: 60,
    serviceArea: '阳光花园小区',
    status: 'active' as const,
    viewCount: 56,
    createdAt: getCurrentTime(),
  },
  {
    id: 'skill-6',
    providerId: 'user-li',
    title: '家政清洁',
    description: '提供家庭日常清洁服务，包括扫地、拖地、擦窗户等。',
    category: '家政服务',
    images: [] as string[],
    timeCoinPrice: 5,
    serviceDuration: 120,
    serviceArea: '阳光花园小区',
    status: 'active' as const,
    viewCount: 78,
    createdAt: getCurrentTime(),
  },
];

const sampleAnnouncements = [
  {
    id: 'announcement-1',
    title: '关于小区自来水管道检修的通知',
    content: '尊敬的业主：\n\n为保障小区供水系统正常运行，物业公司定于2026年6月18日（星期三）上午9:00-12:00对小区供水主管道进行例行检修。\n\n检修期间，1-6号楼将暂停供水，请各位业主提前做好储水准备。检修完成后将逐步恢复供水。\n\n如有任何疑问，请拨打物业热线：400-123-4567\n\n感谢您的理解与配合！\n\n阳光花园物业管理处\n2026年6月14日',
    category: 'water_electricity' as const,
    priority: 'important' as const,
    publisherId: 'user-admin',
    status: 'published' as const,
    viewCount: 128,
    createdAt: '2026-06-14T08:00:00.000Z',
    updatedAt: '2026-06-14T08:00:00.000Z',
  },
  {
    id: 'announcement-2',
    title: '2026年夏季社区运动会报名开始',
    content: '亲爱的邻居们：\n\n为活跃社区文化生活，增进邻里交流，阳光花园社区将于2026年7月6日-7日举办"邻里一家亲"夏季运动会。\n\n比赛项目：\n🏸 羽毛球赛（男女单打、混合双打）\n🏃 趣味接力赛（家庭组）\n♟️ 象棋比赛\n🎯 投篮比赛\n\n报名时间：即日起至6月25日\n报名地点：社区服务中心一楼大厅\n\n奖项设置：各项目前三名可获得精美礼品，所有参与者均有纪念品。\n\n让我们一起运动起来，共享健康生活！\n\n阳光花园社区居委会\n2026年6月12日',
    category: 'community_activity' as const,
    priority: 'normal' as const,
    publisherId: 'user-admin',
    status: 'published' as const,
    viewCount: 256,
    createdAt: '2026-06-12T10:30:00.000Z',
    updatedAt: '2026-06-12T10:30:00.000Z',
  },
  {
    id: 'announcement-3',
    title: '【紧急通知】电梯年度安全检测',
    content: '各位业主：\n\n根据《特种设备安全监察条例》要求，小区电梯将于2026年6月16日进行年度安全检测。\n\n检测时间安排：\n- 1号楼电梯：6月16日 8:00-10:00\n- 2号楼电梯：6月16日 10:00-12:00\n- 3号楼电梯：6月16日 14:00-16:00\n- 4号楼电梯：6月16日 16:00-18:00\n\n检测期间电梯将暂停使用，请高层住户提前做好出行安排。检测完成后立即恢复运行。\n\n给您带来的不便，敬请谅解！\n\n物业24小时值班电话：400-123-4567\n\n阳光花园物业管理处\n2026年6月14日',
    category: 'property' as const,
    priority: 'urgent' as const,
    publisherId: 'user-admin',
    status: 'published' as const,
    viewCount: 342,
    createdAt: '2026-06-14T09:15:00.000Z',
    updatedAt: '2026-06-14T09:15:00.000Z',
  },
  {
    id: 'announcement-4',
    title: '关于小区垃圾分类投放时间调整的通知',
    content: '尊敬的业主：\n\n为进一步提升小区环境质量，配合城市垃圾分类工作要求，自2026年7月1日起，小区垃圾分类投放时间调整如下：\n\n⏰ 投放时间：\n- 早间：7:00-9:00\n- 晚间：18:00-20:00\n\n📍 投放地点：\n各单元楼下智能垃圾分类箱\n\n请各位业主自觉遵守投放时间，将垃圾正确分类投放。物业将在调整初期安排志愿者进行现场指导。\n\n垃圾分类，从我做起！共建美好家园！\n\n阳光花园社区居委会\n2026年6月10日',
    category: 'property' as const,
    priority: 'normal' as const,
    publisherId: 'user-admin',
    status: 'published' as const,
    viewCount: 189,
    createdAt: '2026-06-10T14:00:00.000Z',
    updatedAt: '2026-06-10T14:00:00.000Z',
  },
  {
    id: 'announcement-5',
    title: '6月18日全小区停电检修通知',
    content: '尊敬的业主：\n\n接供电部门通知，为确保夏季用电高峰期间电网安全运行，将于2026年6月18日对小区供电设施进行全面检修。\n\n🕐 停电时间：\n2026年6月18日 22:00 - 次日6:00\n\n🏢 停电范围：\n阳光花园小区全区域\n\n⚠️ 注意事项：\n1. 请提前关闭家中电器设备电源，避免送电时损坏\n2. 冰箱、冰柜尽量减少开门次数\n3. 请准备好手电筒、蜡烛等应急照明设备\n4. 电梯将在停电前10分钟停止运行\n\n预计6月19日6:00恢复供电，如有特殊情况将另行通知。\n\n给您带来的不便，敬请谅解！\n\n供电服务热线：95598\n物业值班电话：400-123-4567\n\n阳光花园物业管理处\n2026年6月13日',
    category: 'water_electricity' as const,
    priority: 'urgent' as const,
    publisherId: 'user-admin',
    status: 'published' as const,
    viewCount: 456,
    createdAt: '2026-06-13T16:45:00.000Z',
    updatedAt: '2026-06-13T16:45:00.000Z',
  },
];

const sampleExchangeItems = [
  {
    id: 'ex-item-1',
    name: '精品保温杯',
    description: '304不锈钢真空保温杯，500ml大容量，12小时保温保冷。适合办公、户外使用。',
    category: 'physical' as const,
    images: ['https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=400'],
    coinPrice: 15,
    stock: 30,
    soldCount: 12,
    status: 'active' as const,
    terms: '请凭兑换码到社区服务中心领取，领取时间：工作日 9:00-17:00',
    createdAt: getCurrentTime(),
    updatedAt: getCurrentTime(),
  },
  {
    id: 'ex-item-2',
    name: '有机大米5kg装',
    description: '东北五常有机大米，5kg家庭装，无农药无化肥，健康美味。',
    category: 'physical' as const,
    images: ['https://images.unsplash.com/photo-1586201375761-83865001e31c?w=400'],
    coinPrice: 25,
    stock: 20,
    soldCount: 8,
    status: 'active' as const,
    terms: '请凭兑换码到社区服务中心领取，每周五下午统一发放',
    createdAt: getCurrentTime(),
    updatedAt: getCurrentTime(),
  },
  {
    id: 'ex-item-3',
    name: '家用清洁套装',
    description: '环保清洁套装：多功能清洁剂2瓶 + 超细纤维抹布3条 + 清洁手套2副',
    category: 'physical' as const,
    images: ['https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=400'],
    coinPrice: 10,
    stock: 50,
    soldCount: 23,
    status: 'active' as const,
    terms: '请凭兑换码到社区服务中心领取',
    createdAt: getCurrentTime(),
    updatedAt: getCurrentTime(),
  },
  {
    id: 'ex-item-4',
    name: '家政清洁2小时券',
    description: '可兑换2小时专业家政清洁服务，包括卧室、客厅、厨房、卫生间清洁。',
    category: 'service_voucher' as const,
    images: ['https://images.unsplash.com/photo-1527515545081-5db817172677?w=400'],
    coinPrice: 20,
    stock: 40,
    soldCount: 15,
    status: 'active' as const,
    terms: '请提前24小时预约服务，服务范围：阳光花园小区内。有效期30天。',
    validDays: 30,
    createdAt: getCurrentTime(),
    updatedAt: getCurrentTime(),
  },
  {
    id: 'ex-item-5',
    name: '儿童绘本借阅月卡',
    description: '社区图书馆儿童绘本区无限次借阅月卡，适合2-12岁儿童。',
    category: 'service_voucher' as const,
    images: ['https://images.unsplash.com/photo-1512820790803-83ca734da794?w=400'],
    coinPrice: 12,
    stock: 100,
    soldCount: 35,
    status: 'active' as const,
    terms: '凭券码到社区图书馆开通，开通后30天内有效。每次最多借阅5本。',
    validDays: 30,
    createdAt: getCurrentTime(),
    updatedAt: getCurrentTime(),
  },
  {
    id: 'ex-item-6',
    name: '社区食堂双人餐券',
    description: '可兑换社区食堂双人套餐一份，两荤两素+汤+米饭。',
    category: 'service_voucher' as const,
    images: ['https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=400'],
    coinPrice: 8,
    stock: 60,
    soldCount: 42,
    status: 'active' as const,
    terms: '营业时间：11:30-13:00, 17:30-19:00。有效期14天。',
    validDays: 14,
    createdAt: getCurrentTime(),
    updatedAt: getCurrentTime(),
  },
  {
    id: 'ex-item-7',
    name: '绿植多肉盆栽',
    description: '精选多肉植物组合盆栽，含精美花盆，适合办公室和居家装饰。',
    category: 'physical' as const,
    images: ['https://images.unsplash.com/photo-1459411552884-841db9b3cc2a?w=400'],
    coinPrice: 8,
    stock: 3,
    soldCount: 18,
    status: 'active' as const,
    terms: '请凭兑换码到社区服务中心领取，数量有限先到先得',
    createdAt: getCurrentTime(),
    updatedAt: getCurrentTime(),
  },
  {
    id: 'ex-item-8',
    name: '家电维修上门券',
    description: '可兑换一次家电维修上门服务，含30分钟检测费用。适用于小型家电维修。',
    category: 'service_voucher' as const,
    images: ['https://images.unsplash.com/photo-1621905252507-b35492cc74b4?w=400'],
    coinPrice: 18,
    stock: 0,
    soldCount: 28,
    status: 'sold_out' as const,
    terms: '请提前预约，服务范围：阳光花园小区。更换零件需另付费。有效期60天。',
    validDays: 60,
    createdAt: getCurrentTime(),
    updatedAt: getCurrentTime(),
  },
];

const sampleDemands = [
  {
    id: 'demand-1',
    requesterId: 'user-zhang',
    title: '急需一个冲击钻',
    description: '家里要装几幅挂画和置物架，需要冲击钻打孔，使用时间大概2小时，可以上门自取或约时间使用。',
    type: 'item' as const,
    category: '工具',
    images: [] as string[],
    timeCoinReward: 3,
    urgency: 'urgent' as const,
    contactPhone: '13800000001',
    contactAddress: '阳光花园小区3号楼502',
    status: 'open' as const,
    viewCount: 28,
    createdAt: getCurrentTime(),
    updatedAt: getCurrentTime(),
  },
  {
    id: 'demand-2',
    requesterId: 'user-li',
    title: '求帮忙搬家',
    description: '周六上午需要帮忙搬家，东西不多，主要是几个纸箱和家具，从5楼搬到同小区另一栋3楼，有电梯。大概需要2-3人，预计2小时完成。',
    type: 'service' as const,
    category: '搬运服务',
    images: [] as string[],
    timeCoinReward: 8,
    urgency: 'normal' as const,
    contactPhone: '13800000002',
    contactAddress: '阳光花园小区2号楼',
    status: 'open' as const,
    viewCount: 45,
    createdAt: getCurrentTime(),
    updatedAt: getCurrentTime(),
  },
  {
    id: 'demand-3',
    requesterId: 'user-chen',
    title: '借用电饭煲',
    description: '家里电饭煲坏了，新的还没到，借用2-3天，用完会清洗干净归还。',
    type: 'item' as const,
    category: '家电',
    images: [] as string[],
    timeCoinReward: 2,
    urgency: 'normal' as const,
    contactPhone: '13800000004',
    contactAddress: '阳光花园小区1号楼301',
    status: 'responding' as const,
    viewCount: 15,
    createdAt: getCurrentTime(),
    updatedAt: getCurrentTime(),
  },
  {
    id: 'demand-4',
    requesterId: 'user-wang',
    title: '需要电脑维修',
    description: '笔记本电脑开不了机，可能是系统问题，希望有懂电脑的邻居帮忙看看，感谢！',
    type: 'service' as const,
    category: '维修服务',
    images: [] as string[],
    timeCoinReward: 5,
    urgency: 'very_urgent' as const,
    contactPhone: '13800000003',
    contactAddress: '阳光花园小区4号楼201',
    status: 'open' as const,
    viewCount: 62,
    createdAt: getCurrentTime(),
    updatedAt: getCurrentTime(),
  },
];

const sampleDemandResponses = [
  {
    id: 'demand-response-1',
    demandId: 'demand-3',
    responderId: 'user-zhang',
    message: '我家里有个闲置的电饭煲，可以借你用，明天给你送过去。',
    status: 'pending' as const,
    createdAt: getCurrentTime(),
  },
];

const sampleGreetingCardTemplates = [
  {
    id: 'template-thanks-1',
    title: '谢谢你的帮助',
    content: '非常感谢您的热心帮助，让我顺利完成了这件事！您的善良让社区更温暖。',
    category: 'thanks' as const,
    emoji: '🙏',
    bgColor: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
    textColor: '#ffffff',
    sortOrder: 1,
  },
  {
    id: 'template-thanks-2',
    title: '万分感谢',
    content: '真的太感谢了！有您这样的好邻居，是我们的幸运。以后有需要我帮忙的地方，尽管开口！',
    category: 'thanks' as const,
    emoji: '💝',
    bgColor: 'linear-gradient(135deg, #f093fb 0%, #f5576c 100%)',
    textColor: '#ffffff',
    sortOrder: 2,
  },
  {
    id: 'template-cooperation-1',
    title: '合作愉快',
    content: '这次合作非常愉快！期待下次有机会继续合作。祝您生活愉快！',
    category: 'cooperation' as const,
    emoji: '🤝',
    bgColor: 'linear-gradient(135deg, #4facfe 0%, #00f2fe 100%)',
    textColor: '#ffffff',
    sortOrder: 3,
  },
  {
    id: 'template-cooperation-2',
    title: '期待下次合作',
    content: '这次的交流很愉快，您的专业和认真让我印象深刻。希望以后能有更多合作机会！',
    category: 'cooperation' as const,
    emoji: '✨',
    bgColor: 'linear-gradient(135deg, #43e97b 0%, #38f9d7 100%)',
    textColor: '#ffffff',
    sortOrder: 4,
  },
  {
    id: 'template-appreciation-1',
    title: '您真棒',
    content: '您的技能真的太厉害了！能认识您这样的邻居，我感到很高兴。',
    category: 'appreciation' as const,
    emoji: '👍',
    bgColor: 'linear-gradient(135deg, #fa709a 0%, #fee140 100%)',
    textColor: '#ffffff',
    sortOrder: 5,
  },
  {
    id: 'template-appreciation-2',
    title: '为您点赞',
    content: '您的服务态度和专业水平都让我非常满意，必须给您点个大大的赞！',
    category: 'appreciation' as const,
    emoji: '🌟',
    bgColor: 'linear-gradient(135deg, #ffecd2 0%, #fcb69f 100%)',
    textColor: '#8b4513',
    sortOrder: 6,
  },
  {
    id: 'template-encouragement-1',
    title: '加油',
    content: '您做得很棒！继续保持，相信您会越来越好。社区因为有您而更加美好！',
    category: 'encouragement' as const,
    emoji: '💪',
    bgColor: 'linear-gradient(135deg, #a8edea 0%, #fed6e3 100%)',
    textColor: '#4a5568',
    sortOrder: 7,
  },
  {
    id: 'template-encouragement-2',
    title: '一起加油',
    content: '邻里互助，温暖你我。让我们一起把社区建设得更美好！',
    category: 'encouragement' as const,
    emoji: '🌈',
    bgColor: 'linear-gradient(135deg, #ff9a9e 0%, #fecfef 50%, #fecfef 100%)',
    textColor: '#8b4513',
    sortOrder: 8,
  },
];

export function initializeSampleData() {
  const collections = {
    users: sampleUsers,
    items: sampleItems,
    skills: sampleSkills,
    exchangeItems: sampleExchangeItems,
    announcements: sampleAnnouncements,
    demands: sampleDemands,
    demandResponses: sampleDemandResponses,
    demandOrders: [],
    borrowOrders: [],
    serviceOrders: [],
    exchangeRecords: [],
    reviews: [],
    disputes: [],
    depositTransactions: [],
    timeCoinTransactions: [],
    favorites: [],
    follows: [],
    greetingCardTemplates: sampleGreetingCardTemplates,
    greetingCards: [],
  };

  db.initializeData(collections);

  console.log('✅ 示例数据初始化完成');
  console.log('   - 用户：' + sampleUsers.length + ' 个');
  console.log('   - 物品：' + sampleItems.length + ' 个');
  console.log('   - 技能：' + sampleSkills.length + ' 个');
  console.log('   - 兑换商品：' + sampleExchangeItems.length + ' 个');
  console.log('   - 社区公告：' + sampleAnnouncements.length + ' 条');
  console.log('   - 需求广场：' + sampleDemands.length + ' 条');
  console.log('   - 感谢卡片模板：' + sampleGreetingCardTemplates.length + ' 个');
  console.log('');
  console.log('📋 测试账号：');
  console.log('   管理员：admin@example.com / admin123');
  console.log('   普通用户：zhang@example.com / 123456');
  console.log('   普通用户：li@example.com / 123456');
}

// 如果直接运行此文件，则执行初始化
if (require.main === module) {
  initializeSampleData();
  console.log('\n🚀 数据初始化完成！');
}
